name: defect-detection
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.*
  - torchvision=0.*
  - lightning=2.*
  - torchmetrics=1.*
  - hydra-core=1.*
  - mlflow
  - rich=13.*
  - pre-commit=3.*
  - pytest=7.*
  - numpy
  - pandas
  - matplotlib
  - scienceplots
  - scikit-learn
  - tqdm
  - seaborn
  - ipykernel
  - optuna
  - dvc
  - pip>=23
  - pip:
    - hydra-optuna-sweeper
    - optuna-integration[pytorch_lightning]
    - hydra-colorlog
    - rootutils
    - "git+https://github.com/cleanlab/cleanlab.git#egg=cleanlab[datalab]"
    - "git+https://github.com/openai/CLIP.git"