# @package _global_

optimized_metric: "val/f1_best"
direction: maximize

study_name: null

n_jobs: 1

n_trials: 20

search_space:
  model:
    optimizer:
      lr:
        type: "float"
        low: 1.0e-5
        high: 1.0e-2
        log: true
      weight_decay:
        type: "float"
        low: 1.0e-6
        high: 1.0e-2
        log: true
  
  data:
    batch_size:
      type: "categorical"
      choices: [32, 64, 96, 128]
  
  # Add more hyperparameters as needed
  # trainer:
  #   max_epochs:
  #     type: "int"
  #     low: 50
  #     high: 200