# @package _global_

defaults:
  - default
  - _self_

study_name: mixup_nce_rce

search_space:
  mixup:
    alpha:
      type: float
      low: 0.01
      high: 3.0
      log: true
  loss:
    alpha:
      type: float
      low: 0.001
      high: 20
      log: true
    beta:
      type: float
      low: 0.001
      high: 20
      log: true
  
