# @package _global_

defaults:
  - default
  - _self_

study_name: nce_rce

search_space:
  loss:
    alpha:
      type: float
      low: 0.001
      high: 20
      log: true
    beta:
      type: float
      low: 0.001
      high: 20
      log: true
  
