_target_: src.models.base_robust_module.BaseRobustModule

num_classes: 9

net:
  _target_: src.models.components.mobile_net.MobileNet
  num_classes: ${model.num_classes}
  pretrained: true
  variant: small

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.01
  weight_decay: 1e-4

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${trainer.max_epochs}

criterion:
  _target_: src.models.components.loss.CELoss
  _partial_: true

compile: false
