_target_: src.models.cutmix_module.CutMixModule

num_classes: 10

net:
  _target_: src.models.components.mobile_net.MobileNet
  num_classes: ${model.num_classes}
  pretrained: true
  variant: small

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.01
  momentum: 0.9
  weight_decay: 1e-4

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${trainer.max_epochs}

criterion:
  _target_: src.models.components.loss.CELoss
  _partial_: true

mixup_alpha: 0.5
cutmix_alpha: 0.5
compile: false
