_target_: src.models.mixup_module.MixupModule

num_classes: 9

net:
  _target_: src.models.components.mobile_net.MobileNet
  num_classes: ${model.num_classes}
  pretrained: true
  variant: large

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${trainer.max_epochs}

criterion:
  _target_: src.models.components.loss.CELoss
  _partial_: true

mixup_alpha: 0.2
compile: false
