_target_: src.models.noise_adaption_module.NoiseAdaptionModule

num_classes: 9

net:
  _target_: src.models.components.mobile_net.MobileNet
  num_classes: ${model.num_classes}
  pretrained: true
  variant: small

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: ${trainer.max_epochs}

criterion:
  _target_: src.models.components.loss.CELoss
  _partial_: true

noise_init_epoch: 5
noise_instance_epoch: 10
instance_hidden_dim: 128
noise_init_eps: 1.0e-6
noise_matrix_path: /home/lukasb/Documents/NoisyLabelDefectDetection/notebooks/data_cleaning/artifacts/noise_estimation/noise_matrix.pt
compile: false
