# @package _global_

defaults:
  - paths: default
  - trainer: gpu
  - callbacks: default
  - data: surface_data
  - experiment: null
  - hparams_search: default
  - _self_

research_name: SurfaceDefectDetection

log_path: ./logs

seed: 42

hydra:
  run:
    dir: ${log_path}/sweep/${research_name}/${experiment_name}/${run_name}