# @package _global_

defaults:
  - _self_
  - paths: default
  - trainer: gpu
  - callbacks: with_early_stopping
  - data: holdout
  - experiment: null

research_name: SurfaceDefectDetection
run_name_postfix: ""
run_name: "${now:%Y-%m-%d_%H-%M-%S}_${run_name_postfix}"

log_path: ./logs

seed: 42
n_runs: 10
run_test: true

hydra:
  run:
    dir: ${log_path}/train/${research_name}/${experiment_name}/${run_name}