# @package _global_

defaults:
  - _self_
  - paths: default
  - trainer: gpu
  - callbacks: default
  - data: surface_data
  - experiment: null

research_name: SurfaceDefectDetection

log_path: ./logs

seed: 42
n_runs: 10

data:
  batch_size: 32
  num_workers: 4

hydra:
  run:
    dir: ${log_path}/train/${research_name}/${experiment_name}/${run_name}